import { StyleSheet, Dimensions } from "react-native";
const { width } = Dimensions.get("window");

export const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: "#F5F7FA",
      marginTop: 15,
    },
    header: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingHorizontal: 20,
      paddingVertical: 15,
      backgroundColor: "#FFF",
    },
    userInfo: {
      flexDirection: "row",
      alignItems: "center",
    },
    avatarContainer: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: "#4F8EF7",
      justifyContent: "center",
      alignItems: "center",
      marginRight: 10,
    },
    avatarText: {
      color: "#FFF",
      fontSize: 18,
      fontWeight: "bold",
    },
    greeting: {
      fontSize: 16,
      fontWeight: "bold",
      color: "#333",
    },
    subGreeting: {
      fontSize: 12,
      color: "#666",
    },
    headerIcons: {
      flexDirection: "row",
    },
    iconContainer: {
      marginLeft: 15,
      position: "relative",
    },
    badge: {
      position: "absolute",
      right: -6,
      top: -6,
      backgroundColor: "#FF3B30",
      borderRadius: 8,
      width: 16,
      height: 16,
      justifyContent: "center",
      alignItems: "center",
    },
    badgeText: {
      color: "#FFF",
      fontSize: 10,
      fontWeight: "bold",
    },
    streakContainer: {
      flexDirection: "row",
      backgroundColor: "#FFF",
      marginHorizontal: 20,
      marginTop: 15,
      borderRadius: 12,
      padding: 15,
      elevation: 2,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
    },
    streakItem: {
      flexDirection: "row",
      alignItems: "center",
      flex: 1,
    },
    iconBackground: {
      width: 40,
      height: 40,
      borderRadius: 20,
      justifyContent: "center",
      alignItems: "center",
      marginRight: 10,
    },
    streakTitle: {
      fontSize: 12,
      color: "#666",
    },
    streakValue: {
      fontSize: 16,
      fontWeight: "bold",
      color: "#333",
    },
    separator: {
      width: 1,
      height: "70%",
      backgroundColor: "#E0E0E0",
      marginHorizontal: 10,
    },
    sectionContainer: {
      marginHorizontal: 20,
      marginTop: 20,
    },
    sectionHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 10,
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: "bold",
      color: "#333",
    },
    seeAll: {
      fontSize: 12,
      color: "#4F8EF7",
      fontWeight: "600",
    },
    courseCard: {
      width: width * 0.65,
      backgroundColor: "#FFF",
      borderRadius: 12,
      marginRight: 15,
      overflow: "hidden",
      elevation: 2,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
    },
    courseImage: {
      width: "100%",
      height: 100,
      resizeMode: "cover",
    },
    courseInfo: {
      padding: 15,
    },
    courseTitle: {
      fontSize: 16,
      fontWeight: "bold",
      color: "#333",
      marginBottom: 8,
    },
    progressBarContainer: {
      height: 6,
      backgroundColor: "#E0E0E0",
      borderRadius: 3,
      overflow: "hidden",
      marginBottom: 5,
    },
    progressBar: {
      height: "100%",
      backgroundColor: "#4F8EF7",
      borderRadius: 3,
    },
    progressText: {
      fontSize: 12,
      color: "#666",
    },
    activitiesContainer: {
      flexDirection: "row",
      flexWrap: "wrap",
      justifyContent: "space-between",
    },
    activityItem: {
      width: "48%",
      backgroundColor: "#FFF",
      borderRadius: 12,
      padding: 15,
      marginBottom: 15,
      alignItems: "center",
      elevation: 2,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
    },
    activityIconContainer: {
      width: 50,
      height: 50,
      borderRadius: 25,
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 10,
    },
    activityTitle: {
      fontSize: 14,
      fontWeight: "600",
      color: "#333",
      textAlign: "center",
    },
    categoriesContainer: {
      marginTop: 5,
    },
    categoryCard: {
      flexDirection: "row",
      backgroundColor: "#FFF",
      borderRadius: 12,
      padding: 15,
      marginBottom: 15,
      justifyContent: "space-between",
      alignItems: "center",
      elevation: 2,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
    },
    categoryContent: {
      flex: 1,
    },
    categoryIconContainer: {
      width: 50,
      height: 50,
      borderRadius: 25,
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 10,
    },
    categoryTitle: {
      fontSize: 16,
      fontWeight: "bold",
      color: "#333",
      marginBottom: 5,
    },
    categoryDescription: {
      fontSize: 12,
      color: "#666",
    },
    categoryImage: {
      width: 80,
      height: 80,
      resizeMode: "contain",
    },
    achievementContainer: {
      marginHorizontal: 20,
      marginTop: 20,
      borderRadius: 12,
      overflow: "hidden",
      elevation: 2,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
    },
    achievementGradient: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      padding: 20,
    },
    achievementContent: {
      flexDirection: "row",
      alignItems: "center",
    },
    achievementIconContainer: {
      marginRight: 15,
    },
    achievementTextContainer: {
      flex: 1,
    },
    achievementTitle: {
      fontSize: 16,
      fontWeight: "bold",
      color: "#FFF",
      marginBottom: 5,
    },
    achievementDescription: {
      fontSize: 12,
      color: "#FFF",
      opacity: 0.8,
    },
  });